#  AutoBroadcaster Configuration File
#  ----------------------------------------------------
#  Message Configuration:
#     Messages are handled in lists to allow for advanced customization!
#     Feel free to add color codes by using & in your messages!
#     To split a message onto multiple lines use the \n delimiter!
#     Lines starting with / will be run as a command!
#     To add single apostrophes into a message use ''.
#     For a complete tutorial go to https://github.com/thealzhe/mc-abc
#     If you are unfamiliar with YAML use the in-game commands: /abc help

settings:
  enabled: true
  min-players: 0
  log-to-console: false
message-lists:
  regular:
    enabled: true
    random: false
    interval: 45
    expiry: -1
    messages:
    - '&7&oFirst message !'
    - '&7&oSecond message in the list with formatters!'
    - '&7&oThird message in the list with formatters and an\n&7&oanother new line!'
    - '&7&oThese messages will be displayed to users with abc.receive.regular!'