name: AutoBroadcaster
version: ${project.version}
author: thealzhe
description: Create and schedule easy automated server broadcasts!
website: https://alzhe.tv/
main: tv.alzhe.abc.AutoBroadcaster
api-version: 1.19
commands:
   autobroadcaster:
     description: Main command of ABC.
     aliases: [autobc, abc]